DROP TABLE segment CASCADE CONSTRAINT;
DROP TABLE salle CASCADE CONSTRAINT; 
DROP TABLE POSTE CASCADE CONSTRAINT;
DROP TABLE LOGICIEL CASCADE CONSTRAINT;
DROP TABLE INSTALLER;
DROP TABLE TYPES CASCADE CONSTRAINT;