
DROP TABLE vol_jour;
DROP TABLE compagnie;

CREATE TABLE vol_jour (
    NUM_VOL VARCHAR2(6) NOT NULL,
    AERO_DEP VARCHAR2(3) CONSTRAINT nn_depart NOT NULL,
    AERO_ARR VARCHAR2(3) CONSTRAINT nn_arrivee NOT NULL,
    COMP VARCHAR2(4) DEFAULT 'AF',
    JOUR_VOL DATE NOT NULL,
    NB_PASSAGERS NUMBER(3),
    CONSTRAINT pk_vol_jour PRIMARY KEY (NUM_VOL,JOUR_VOL),
    CONSTRAINT fk_vol_jour_comp_compagnie FOREIGN KEY(comp) REFERENCES COMPAGNIE(comp),
    CONSTRAINT ck_nb_pax CHECK (NB_PASSAGERS>0),
    CONSTRAINT ck_trajet CHECK (AERO_DEP != AERO_ARR)
);

CREATE TABLE COMPAGNIE(
    COMP VARCHAR2(4),
    NOM_COMP VARCHAR2(15),
    DATE_CREATION DATE CONSTRAINT nn_date_crea NOT NULL,
    CONSTRAINT pk_compagnie PRIMARY KEY (comp)
);


DESC VOL_JOUR;
COMMENT ON TABLE COMPAGNIE IS 'table des compagnies aériennes françaises';
COMMENT ON COLUMN COMPAGNIE.COMP IS 'Code abréviation de la compagnie';
COMMENT ON COLUMN COMPAGNIE.NOM_COMP IS 'un mauvais commentaire'; 
